#this is a basic workflow to help you get started with Actions

name: CI
# Control de cuando el workflow se ejecutara
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allows you to run this workflow manually from the actions tab
  workflow_dispatch:
#A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called build
  build:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #check repository under $GITHUB_WORKSPACE,  so your job can acces it
      - uses: actions/checkout@v3

      # runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, World!

     # # runs a set of command using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
